const reducerTasks={
    NEW_TASK:"NEW_TASK",
    MAKE_IMPORTANT:"MAKE_IMPORTANT",
    COMPLETED:"COMPLETED",
    DELETE:"DELETE",
    ASCENDING:"ASCENDING",
    DESCENDING:"DESCENDING",
    IMPORTANCE:"IMPORTANCE",
    TIME_UP:"TIME_UP",
    TIME_DOWN:"TIME_DOWN",
    PURPLE_THEME:"PURPLE_THEME",
    BLACK_THEME:"BLACK_THEME",
    WHITE_THEME:"WHITE_THEME",
    RED_THEME:"RED_THEME",
    FETCH_ALL_TASKS:"FETCH_ALL_TASKS"
}
export default reducerTasks;